management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health
  health:
    circuitbreakers:
      enabled: true
resilience4j.circuitbreaker:
  configs:
    default:
      registerHealthIndicator: true